# workflow
name: CI/CD Workflow
run-name: ${{github.actor}} is testing out Github Actions
on: 
  push:
    branches:
    - master

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - run: echo "Job automatically triggered"
      - run: echo "Your Branch ${{github.ref}} and Repo ${{github.repository}}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Checkout Repository
        uses: actions/checkout@v2

